Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-05, with the labels that each got.

#385 /jaのURLにアクセスした際に、/jaなしのURLにredirectできるようにjsで実装する
  custom_theme/404.html
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation, Enhancement

#386 スマートフォンのためのワールド軽量化: Build Optionの記載を追記
  docs/WorldOptimization/SmartphoneOptimization.en.md
  docs/WorldOptimization/SmartphoneOptimization.ja.md
Labels: Review effort [1-5]: 2, Documentation

#387 BrokerAPI: API使用時はワールドアップロードが必要の旨、追記
  docs/ExternalAPI/BrokerAPI.en.md
  docs/ExternalAPI/BrokerAPI.ja.md
Labels: Review effort [1-5]: 2, Documentation

#388 ワールドの基本要素: オブジェクト名の最新化
  docs/FirstStep/WorldBasicComponents.en.md
  docs/FirstStep/WorldBasicComponents.ja.md
Labels: Review effort [1-5]: 2, Documentation

#390 AvatarFile: 'HEOWorldSetting' から ' Avatar Settings'へ記載修正
  docs/WorldMakingGuide/AvatarFile.en.md
  docs/WorldMakingGuide/AvatarFile.ja.md
Labels: Review effort [1-5]: 2, Documentation

#389 PropAnimation: 画像リンクを修正
  docs/WorldMakingGuide/PropAnimation.en.md
  docs/WorldMakingGuide/PropAnimation.ja.md
Labels: bug, Review effort [1-5]: 1, Documentation

#392 HeliScript関連ドキュメントのタイポ・フォーマットを修正
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_list.en.md
  docs/hs/hs_list.ja.md
Labels: Review effort [1-5]: 1, Documentation

#391 Feature/add heocylindercollider: HEOCylinderColliderのページを追加
  docs/HEOComponents/HEOCylinderCollider.en.md
  docs/HEOComponents/HEOCylinderCollider.ja.md
  docs/HEOComponents/img/HEOCylinderCollider_01.jpg
  docs/HEOComponents/img/HEOCylinderCollider_02.jpg
  docs/HEOComponents/img/HEOCylinderCollider_03.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#393 About VketCloudSDK: Standard Shader関連の設定変更の解説画像を更新
  docs/AboutVketCloudSDK/OperatingEnvironment.en.md
  docs/AboutVketCloudSDK/OperatingEnvironment.ja.md
  docs/AboutVketCloudSDK/SetupSDK_external.en.md
  docs/AboutVketCloudSDK/SetupSDK_external.ja.md
  docs/heoexporter/he_align_unity_to_vketcloud.en.md
  docs/heoexporter/he_align_unity_to_vketcloud.ja.md
  docs/heoexporter/he_image/OpenGraphics.jpg
  docs/heoexporter/he_image/OpenGraphics_1.jpg
  docs/heoexporter/he_image/OpenGraphics_2.jpg
  docs/heoexporter/he_image/StandardShaderQuality.jpg
  docs/heoexporter/he_image/TierSettings.jpg
Labels: Review effort [1-5]: 1, Documentation

#395 UnityGuideLines: 使用可能な文字に関する仕様を追記し、caution --> warningに変更
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation

#394 hs_overview: HeliScriptについての表現を変更
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  docs/hs/hs_overview.en.md
  docs/hs/hs_overview.ja.md
Labels: Review effort [1-5]: 1, Documentation
