Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-09, with the labels that each got.

#498 PlayerクラスにCameraRotateの引数を追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_player.en.md
  docs/hs/hs_class_player.ja.md
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#497 GetPosとGetWorldPosの説明の使い分けを説明する
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1, Documentation

#501 Lib13.8リリースノート追加（9/12午前10時公開）
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  docs/releasenote/releasenote-13.8.en.md
  docs/releasenote/releasenote-13.8.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#508 [13.7]Itemクラスページのデフォルト展開と、各コンポーネントページにメソッド一覧追記
  docs/VKCComponents/VKCItemActivity.en.md
  docs/VKCComponents/VKCItemActivity.ja.md
  docs/VKCComponents/VKCItemAreaCollider.en.md
  docs/VKCComponents/VKCItemAreaCollider.ja.md
  docs/VKCComponents/VKCItemAudio.en.md
  docs/VKCComponents/VKCItemAudio.ja.md
  docs/VKCComponents/VKCItemBackgroundTexture.en.md
  docs/VKCComponents/VKCItemBackgroundTexture.ja.md
  docs/VKCComponents/VKCItemCamera.en.md
  docs/VKCComponents/VKCItemCamera.ja.md
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 2, Documentation

#499 【13.4】pngしか受け付けないことを明示する
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#504 【13.7】pngしか受け付けないことを明示する
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation

#502 推奨するIDEについて追記
  docs/AboutVketCloudSDK/OperatingEnvironment.en.md
  docs/AboutVketCloudSDK/OperatingEnvironment.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  docs/hs/hs_overview.en.md
  docs/hs/hs_overview.ja.md
Labels: Review effort [1-5]: 1, Documentation

#505 【13.7】VKC Node Alpha Animationのページで、スペースなし表示になっている。
  docs/VKCComponents/VKCNodeAlphaAnimation.en.md
  docs/VKCComponents/VKCNodeAlphaAnimation.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation

#506 【13.4】VKC Node Alpha Animationのページで、スペースなし表示になっている。
  docs/VKCComponents/VKCNodeAlphaAnimation.en.md
  docs/VKCComponents/VKCNodeAlphaAnimation.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#510 [v13.7] ShaderAvailability: ページを追加し、UnityGuidelinesにて案内を追記
  docs/WorldMakingGuide/ShaderAvailability.en.md
  docs/WorldMakingGuide/ShaderAvailability.ja.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/WorldMakingGuide/img/ShaderAvailability_1.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_2.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_3.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_4.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_5.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_6.jpg
  docs/WorldMakingGuide/img/ShaderAvailability_7.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#507 Vkc node blend shape translatorの情報を追加
  docs/VKCComponents/VKCNodeBlendShapeTranslator.en.md
  docs/VKCComponents/VKCNodeBlendShapeTranslator.ja.md
  docs/VKCComponents/img/VKCNodeBlendShapeTranslator_1.jpg
  docs/VKCComponents/img/VKCNodeBlendShapeTranslator_2.jpg
  docs/VKCComponents/img/VKCNodeBlendShapeTranslator_3.jpg
  docs/VKCComponents/img/VKCNodeBlendShapeTranslator_4.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation

#511 JS入稿のサンプルについてのページを追加
  docs/WorldMakingGuide/JsUpload.en.md
  docs/WorldMakingGuide/JsUpload.ja.md
  docs/WorldMakingGuide/JsUpload_Sample.en.md
  docs/WorldMakingGuide/JsUpload_Sample.ja.md
  docs/WorldMakingGuide/img/JSUpload_SampleWorld.gif
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#512 [13.4]各コンポーネントページにメソッド一覧追記
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/VKCComponents/VKCItemParticle.en.md
  docs/VKCComponents/VKCItemParticle.ja.md
  docs/VKCComponents/VKCItemPlane.en.md
  docs/VKCComponents/VKCItemPlane.ja.md
  docs/VKCComponents/VKCItemTextPlane.en.md
  docs/VKCComponents/VKCItemTextPlane.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#513 HeliScript概要: リンク修正
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_overview.en.md
  docs/hs/hs_overview.ja.md
Labels: Review effort [1-5]: 1, Documentation

#516 動作環境ページにUnityエディターをVSCodeに変更する方法追記
  docs/AboutVketCloudSDK/OperatingEnvironment.en.md
  docs/AboutVketCloudSDK/OperatingEnvironment.ja.md
  docs/AboutVketCloudSDK/img/OperatingEnvironment_01.jpg
  docs/AboutVketCloudSDK/img/OperatingEnvironment_02.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Documentation

#517 VKCAttributeActionTrigger, ActionsOverview: 画像と説明文の更新
  docs/Actions/ActionsOverview.en.md
  docs/Actions/ActionsOverview.ja.md
  docs/VKCComponents/VKCAttributeActionTrigger.en.md
  docs/VKCComponents/VKCAttributeActionTrigger.ja.md
  docs/VKCComponents/img/HEOActionTrigger.jpg
  docs/VKCComponents/img/VKCAttributeActionTrigger.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation
