Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-04, with the labels that each got.

#371 mkdocs-material及びmkdocs-static-i18nを最新に更新
  mkdocs.yml
  requirements.txt
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#372 hs_operator: 厳密等価と厳密非等価演算子を追加
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  docs/hs/hs_operator.en.md
  docs/hs/hs_operator.ja.md
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#374 Prop Animation / TroubleShooting: Export Motion時の注意を追記
  docs/WorldMakingGuide/PropAnimation.en.md
  docs/WorldMakingGuide/PropAnimation.ja.md
  docs/WorldMakingGuide/PropAnimation_TroubleShooting.en.md
  docs/WorldMakingGuide/PropAnimation_TroubleShooting.ja.md
  docs/WorldMakingGuide/img/PropAnimation_TroubleShooting_13.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation

#378 mkdocs.yml: VketCloudSDK設定が目次から外れていたので修正
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#377 hs_item: SetUVOffsetの原点に関する補足を追記
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1, Documentation

#376 VketCloudの仕様制限：各種リソース仕様の更新
  docs/HEOComponents/HEOPlane.ja.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation

#381 アカウント準備：アカウント取得に関する内容を充実させる
  docs/AboutVketCloudSDK/SetupAccount.en.md
  docs/AboutVketCloudSDK/SetupAccount.ja.md
  docs/AboutVketCloudSDK/img/setupaccount_1.en.jpg
  docs/AboutVketCloudSDK/img/setupaccount_1.ja.jpg
  docs/AboutVketCloudSDK/img/setupaccount_2.en.jpg
  docs/AboutVketCloudSDK/img/setupaccount_2.ja.jpg
  docs/AboutVketCloudSDK/img/setupaccount_3.en.jpg
  docs/AboutVketCloudSDK/img/setupaccount_3.ja.jpg
  docs/AboutVketCloudSDK/img/setupaccount_4.en.jpg
  docs/AboutVketCloudSDK/img/setupaccount_4.ja.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#379 PropAnimation: アニメーション作成時の注意を追記
  docs/WorldMakingGuide/PropAnimation.en.md
  docs/WorldMakingGuide/PropAnimation.ja.md
  docs/WorldMakingGuide/PropAnimation_TroubleShooting.en.md
  docs/WorldMakingGuide/PropAnimation_TroubleShooting.ja.md
  docs/WorldMakingGuide/img/PropAnimation_28.jpg
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation
