Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-07, with the labels that each got.

#419 Avatarfile: ボーン名表記をCamelCase表記に修正
  docs/WorldMakingGuide/AvatarFile.en.md
  docs/WorldMakingGuide/AvatarFile.ja.md
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 1, Documentation

#418 HEOPlane: showのデフォルト値を更新
  docs/HEOComponents/HEOPlane.en.md
  docs/HEOComponents/HEOPlane.ja.md
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 1, Documentation

#426 hs_class_player : ResetVelocity()を追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_player.en.md
  docs/hs/hs_class_player.ja.md
Labels: Review effort [1-5]: 1, Documentation

#427 hs_overview, BuildError, BuildAndRun : HeliScriptエラーの表示方法に関する注意を追記
  docs/FirstStep/BuildAndRun.en.md
  docs/FirstStep/BuildAndRun.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_overview.en.md
  docs/hs/hs_overview.ja.md
  docs/troubleshooting/BuildError.en.md
  docs/troubleshooting/BuildError.ja.md
Labels: Review effort [1-5]: 2, Documentation

#428 WorldUpload : 説明文・画像の最新化
  docs/FirstStep/WorldUpload.en.md
  docs/FirstStep/WorldUpload.ja.md
  docs/FirstStep/img/CheckTheWorld_Web.jpg
  docs/FirstStep/img/CheckTheWorld_WorldUploader.jpg
  docs/FirstStep/img/CreateWorldID.jpg
  docs/FirstStep/img/SuccessfullyUploaded.jpg
  docs/FirstStep/img/TeamName.jpg
  docs/FirstStep/img/WorldListForUpload.jpg
  docs/FirstStep/img/WorldUpload.jpg
  docs/FirstStep/img/WorldUpload01.jpg
  docs/FirstStep/img/WorldUpload02.jpg
  docs/FirstStep/img/WorldUpload03.jpg
  docs/FirstStep/img/WorldUpload04.jpg
  docs/FirstStep/img/WorldUpload05.jpg
  docs/FirstStep/img/WorldUpload06.jpg
  docs/FirstStep/img/WorldUpload07.jpg
  docs/FirstStep/img/WorldUpload08.jpg
  docs/FirstStep/img/WorldUpload09.jpg
  docs/FirstStep/img/WorldUpload10.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Documentation

#429 ActionにWindow状態カテゴリーを追加
  docs/Actions/Fade/FadeOutIn.en.md
  docs/Actions/Fade/FadeOutIn.ja.md
  docs/Actions/Fade/WhiteOutIn.en.md
  docs/Actions/Fade/WhiteOutIn.ja.md
  docs/Actions/Motion/Motion.en.md
  docs/Actions/Motion/NextMotion.en.md
  docs/Actions/Operation/SetVar.en.md
  docs/Actions/Others/SetCookieText.en.md
  docs/Actions/VoiceChat/EnterLeaveVoiceGroup.en.md
  docs/Actions/WindowState/MovieViewerFullScreenOff.en.md
  docs/Actions/WindowState/MovieViewerFullScreenOff.ja.md
  docs/Actions/WindowState/MovieViewerFullScreenOn.en.md
  docs/Actions/WindowState/MovieViewerFullScreenOn.ja.md
  docs/Actions/WindowState/MovieViewerFullScreenToggle.en.md
  docs/Actions/WindowState/MovieViewerFullScreenToggle.ja.md
  docs/Actions/WindowState/OpenMovieViewer.en.md
  docs/Actions/WindowState/OpenMovieViewer.ja.md
  docs/Actions/WindowState/SetGenericWindowState.en.md
  docs/Actions/WindowState/SetGenericWindowState.ja.md
  docs/Actions/WindowState/img/MovieViewerFullScreenOff.jpg
  docs/Actions/WindowState/img/MovieViewerFullScreenOn.jpg
  docs/Actions/WindowState/img/MovieViewerFullScreenToggle.jpg
  docs/Actions/WindowState/img/OpenMovieViewer.jpg
  docs/Actions/WindowState/img/SetGenericWindowState.jpg
  docs/Actions/WindowState/img/SetGenericWindowStateDropdown.jpg
  docs/Actions/WindowState/img/SetGenericWindowStateImageViewer.jpg
  docs/Actions/WindowState/img/SetGenericWindowStateTarget.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#430 Debug console4.0追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/debugconsole/debugmessage.en.md
  docs/debugconsole/debugmessage.ja.md
Labels: Review effort [1-5]: 1, Documentation

#431 可動オブジェクトに関してクリック判定の取り方
  docs/WorldMakingGuide/MovableClickableObject.en.md
  docs/WorldMakingGuide/MovableClickableObject.ja.md
  docs/WorldMakingGuide/img/movable_clickable_cube.jpg
  docs/WorldMakingGuide/img/movable_clickable_floor.jpg
  docs/WorldMakingGuide/img/movable_clickable_item_object.jpg
  docs/WorldMakingGuide/img/movable_clickable_root.jpg
  docs/WorldMakingGuide/img/movable_clickable_run.jpg
  docs/WorldMakingGuide/img/movable_clickable_text.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#433 リリースノート13.5と13.6を追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/releasenote/releasenote-13.4.en.md
  docs/releasenote/releasenote-13.5.en.md
  docs/releasenote/releasenote-13.5.ja.md
  docs/releasenote/releasenote-13.6.en.md
  docs/releasenote/releasenote-13.6.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#434 【13.4】hsGetCurrentWorldIdのデータタイプをfloatからstringに変更
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_system_function.en.md
  docs/hs/hs_system_function.ja.md
Labels: Review effort [1-5]: 1, Documentation, Enhancement

#435 【12.3】hsGetCurrentWorldIdのデータタイプをfloatからstringに変更
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  docs/hs/hs_system_function.en.md
  docs/hs/hs_system_function.ja.md
Labels: Review effort [1-5]: 1, Documentation

#437 VKCItemObject: 内容をSDK13向けに更新
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/VKCComponents/img/HEOObject_1.jpg
  docs/VKCComponents/img/HEOObject_2.jpg
  docs/VKCComponents/img/HEOObject_Motion.jpg
  docs/VKCComponents/img/HEOObject_Motion_Preview.jpg
  docs/VKCComponents/img/HEOObject_Pose.jpg
  docs/VKCComponents/img/HEOObject_Preview.jpg
  docs/VKCComponents/img/VKCItemObject_1.jpg
  docs/VKCComponents/img/VKCItemObject_2.jpg
  docs/VKCComponents/img/VKCItemObject_3.jpg
  docs/VKCComponents/img/VKCItemObject_4.jpg
  docs/VKCComponents/img/VKCItemObject_5.jpg
  docs/VKCComponents/img/VKCItemObject_6.jpg
  docs/VKCComponents/img/VKCItemObject_7.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 2, Documentation

#438 WorldUpload: アップロード時のビルドオプションについて追記
  docs/FirstStep/WorldUpload.en.md
  docs/FirstStep/WorldUpload.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#432 ConvertAnimationFromUntiyAsset : アニメーション変換方法解説ページ作成
  docs/WorldMakingGuide/ConvertAnimationFromUnityAsset.en.md
  docs/WorldMakingGuide/ConvertAnimationFromUnityAsset.ja.md
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_01.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_02.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_03.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_04.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_05.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_06.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_07.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_08.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_09.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_10.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_11.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_12.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_13.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_14.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_15.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_16.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_17.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_18.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_19.gif
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_20.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_21.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_22.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_23.jpg
  docs/WorldMakingGuide/img/ConvertAnimationFromUnityAsset_24.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#440 File Deployment Modeの説明を追加
  docs/VketCloudSettings/BasicSettings.en.md
  docs/VketCloudSettings/BasicSettings.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#441 PlayerSettingsの画像を更新
  docs/VketCloudSettings/img/PlayerSettings_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#442 VKCSettingDespawnHeightの画像を更新
  docs/VketCloudSettings/DespawnHeightSettings.en.md
  docs/VketCloudSettings/DespawnHeightSettings.ja.md
  docs/VketCloudSettings/img/DespawnHeightSettings_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 1, Documentation

#443 VKCItemField: 内容を更新
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/VKCComponents/img/HEOField.jpg
  docs/VKCComponents/img/VKCItemField1.jpg
  docs/VKCComponents/img/VKCItemField2.jpg
  docs/VKCComponents/img/VKCItemField3.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Documentation

#444 VKCNamePlateの画像更新
  docs/VKCComponents/VKCSettingNameplate.en.md
  docs/VKCComponents/VKCSettingNameplate.ja.md
  docs/VKCComponents/img/HEONameplate_1.jpg
  docs/VKCComponents/img/HEONameplate_2.jpg
  docs/VKCComponents/img/VKCSettingNameplate_1.jpg
  docs/VKCComponents/img/VKCSettingNameplate_2.jpg
  docs/VKCComponents/img/VKCSettingNameplate_3.jpg
  docs/VKCComponents/img/VKCSettingNameplate_4.jpg
  docs/VKCComponents/img/VKCSettingNameplate_5.jpg
  docs/VKCComponents/img/VKCSettingNameplate_6.jpg
  docs/VKCComponents/img/VKCSettingNameplate_7.jpg
  docs/VKCComponents/img/VKCSettingNameplate_8.jpg
  docs/VKCComponents/img/VKCSettingNameplate_9.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#449 VKCItemAreaColliderの画像更新と複数項目追加
  docs/VKCComponents/VKCItemAreaCollider.en.md
  docs/VKCComponents/VKCItemAreaCollider.ja.md
  docs/VKCComponents/img/HEOAreaCollider.jpg
  docs/VKCComponents/img/HEOCollider_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 2, Documentation
