Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-06, with the labels that each got.

#396 UnityGuidelines: 使用可能文字とオーディオ・動画に関する英訳
  docs/HEOComponents/HEOAudio.en.md
  docs/HEOComponents/HEOAudio.ja.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-12.3.en.md
Labels: Review effort [1-5]: 2, Documentation

#398 HeliScript: hs_class_playerの未実装関数を削除し、hs_system_function_commondialogのフォーマットの崩れを修正
  docs/hs/hs_class_player.en.md
  docs/hs/hs_class_player.ja.md
  docs/hs/hs_system_function_commondialog.en.md
  docs/hs/hs_system_function_commondialog.ja.md
Labels: Review effort [1-5]: 1, Documentation

#399 説明画像内のアイコンを13.0版に変更
  docs/SDKTools/img/VKCActivityExporter_9.jpg
  docs/hs/img/hs_overview_2.jpg
  docs/hs/img/hs_overview_4.jpg
  docs/troubleshooting/img/HEOWorldSetting_AvatarFileError_1.jpg
  docs/troubleshooting/img/HEOWorldSetting_AvatarFileError_2.jpg
  docs/troubleshooting/img/VersionUpdateTroubleshooting_10.png
  docs/troubleshooting/img/VersionUpdateTroubleshooting_9.jpg
Labels: Documentation

#400 GeneralChecklist:「何か起きたときにとりあえず見るべきリスト」の記載が古い部分を12.3向けに修正
  docs/troubleshooting/GeneralChecklist.en.md
  docs/troubleshooting/GeneralChecklist.ja.md
  docs/troubleshooting/img/GeneralChecklist_12.jpg
Labels: Review effort [1-5]: 2, Documentation

#397 File Deployment Configを追加
  docs/WorldMakingGuide/FileDeploymentConfig.en.md
  docs/WorldMakingGuide/FileDeploymentConfig.ja.md
  docs/WorldMakingGuide/img/filedeploymentconfig_01.jpg
  docs/WorldMakingGuide/img/filedeploymentconfig_02.jpg
  docs/WorldMakingGuide/img/filedeploymentconfig_03.jpg
  docs/WorldMakingGuide/img/filedeploymentconfig_04.jpg
  docs/WorldMakingGuide/img/filedeploymentconfig_05.jpg
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#403 VKCNodeAlphaAnimation : ページを追加
  docs/VKCComponents/VKCNodeAlphaAnimation.en.md
  docs/VKCComponents/VKCNodeAlphaAnimation.ja.md
  docs/VKCComponents/img/VKCNodeAlphaAnimation_01.gif
  docs/VKCComponents/img/VKCNodeAlphaAnimation_02.jpg
  docs/VKCComponents/img/VKCNodeAlphaAnimation_03.jpg
  docs/VKCComponents/img/VKCNodeAlphaAnimation_04.gif
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#402 AvatarFile: AvatarFileページを13.x仕様に刷新
  docs/WorldMakingGuide/AvatarFile.en.md
  docs/WorldMakingGuide/AvatarFile.ja.md
  docs/WorldMakingGuide/img/AvatarFile_1.jpg
  docs/WorldMakingGuide/img/AvatarFile_2.jpg
  docs/WorldMakingGuide/img/AvatarFile_3.jpg
  docs/WorldMakingGuide/img/AvatarFile_4.jpg
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
Labels: Review effort [1-5]: 2, Documentation

#409 SDKログイン時のmacOSユーザ向けの注記を追記
  docs/AboutVketCloudSDK/LoginSDK.en.md
  docs/AboutVketCloudSDK/LoginSDK.ja.md
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
  docs/troubleshooting/InstallingDeeplink.en.md
  docs/troubleshooting/InstallingDeeplink.ja.md
Labels: Review effort [1-5]: 1, Documentation

#411 VKC Node ColliderのCollider Targetに新しい「プレーヤー」項目の追加/押し出し処理パラメータの追加
  docs/VKCComponents/VKCNodeCollider.en.md
  docs/VKCComponents/VKCNodeCollider.ja.md
  docs/VKCComponents/img/VKCNodeCollider_1.jpg
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
Labels: Review effort [1-5]: 2, Documentation

#407 VKC Item Activity(HEOActivity)ページを13.xの仕様に更新
  docs/VKCComponents/VKCItemActivity.en.md
  docs/VKCComponents/VKCItemActivity.ja.md
  docs/VKCComponents/img/HEOActivity_1.jpg
  docs/VKCComponents/img/HEOActivity_10.jpg
  docs/VKCComponents/img/HEOActivity_11.jpg
  docs/VKCComponents/img/HEOActivity_4_en.jpg
  docs/VKCComponents/img/HEOActivity_4_ja.jpg
  docs/VKCComponents/img/HEOActivity_9.jpg
  docs/VKCComponents/img/VKCItemActivity_1.jpg
  docs/VKCComponents/img/VKCItemActivity_10.jpg
  docs/VKCComponents/img/VKCItemActivity_11.jpg
  docs/VKCComponents/img/VKCItemActivity_12.jpg
  docs/VKCComponents/img/VKCItemActivity_13.jpg
  docs/VKCComponents/img/VKCItemActivity_14.jpg
  docs/VKCComponents/img/VKCItemActivity_15.jpg
  docs/VKCComponents/img/VKCItemActivity_16.jpg
  docs/VKCComponents/img/VKCItemActivity_17.jpg
  docs/VKCComponents/img/VKCItemActivity_18.jpg
  docs/VKCComponents/img/VKCItemActivity_19.jpg
  docs/VKCComponents/img/VKCItemActivity_2.jpg
  docs/VKCComponents/img/VKCItemActivity_3.jpg
  docs/VKCComponents/img/VKCItemActivity_4.jpg
  docs/VKCComponents/img/VKCItemActivity_5.jpg
  docs/VKCComponents/img/VKCItemActivity_6.jpg
  docs/VKCComponents/img/VKCItemActivity_7.jpg
  docs/VKCComponents/img/VKCItemActivity_8.jpg
  docs/VKCComponents/img/VKCItemActivity_9.jpg
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
Labels: Documentation

#412 Ver13.0におけるHeliScriptについての追記
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
  docs/hs/hs_class_date.en.md
  docs/hs/hs_class_date.ja.md
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_class_player.ja.md
  docs/hs/hs_component.ja.md
  docs/hs/hs_statement_def.ja.md
  docs/hs/hs_struct_quaternion.ja.md
  docs/hs/hs_struct_vector3.ja.md
  docs/hs/hs_system_function.ja.md
  docs/hs/hs_system_function_camera.ja.md
  docs/hs/hs_system_function_commondialog.ja.md
  docs/hs/hs_system_function_gui.ja.md
  docs/hs/hs_system_function_gui_HSGUIModel.en.md
  docs/hs/hs_system_function_gui_HSGUIModel.ja.md
  docs/hs/hs_system_function_rendering.en.md
  docs/hs/hs_system_function_rendering.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#406 GUITools : 使い方に関するページを追加
  docs/GUITools/AdvancedUse.en.md
  docs/GUITools/AdvancedUse.ja.md
  docs/GUITools/HowToUse.en.md
  docs/GUITools/HowToUse.ja.md
  docs/GUITools/Setup.en.md
  docs/GUITools/Setup.ja.md
  docs/GUITools/img/GUITools_HowToUse_01.jpg
  docs/GUITools/img/GUITools_HowToUse_02.jpg
  docs/GUITools/img/GUITools_HowToUse_03.jpg
  docs/GUITools/img/GUITools_HowToUse_04.jpg
  docs/GUITools/img/GUITools_HowToUse_05.jpg
  docs/GUITools/img/GUITools_HowToUse_06.jpg
  docs/GUITools/img/GUITools_HowToUse_07.jpg
  docs/GUITools/img/GUITools_HowToUse_08.jpg
  docs/GUITools/img/GUITools_HowToUse_09.jpg
  docs/GUITools/img/GUITools_HowToUse_10.jpg
  docs/GUITools/img/GUITools_HowToUse_11.jpg
  docs/GUITools/img/GUITools_HowToUse_12.jpg
  docs/GUITools/img/GUITools_HowToUse_13.jpg
  docs/GUITools/img/GUITools_Setup_01.jpg
  docs/GUITools/img/GUITools_Setup_02.jpg
  docs/GUITools/img/GUITools_Setup_03.jpg
  docs/GUITools/img/GUITools_Setup_04.jpg
  docs/GUITools/img/GUITools_Setup_05.jpg
  docs/GUITools/img/GUITools_Setup_06.jpg
  docs/GUITools/img/GUITools_Setup_07.jpg
  docs/changelog/changelog-13.0.en.md
  docs/changelog/changelog-13.0.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation
