Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-08, with the labels that each got.

#445 VKC Rendering Settings: 画像およびデフォルト値更新
  docs/VketCloudSettings/RenderingSettings.en.md
  docs/VketCloudSettings/RenderingSettings.ja.md
  docs/VketCloudSettings/img/RenderingSettings_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#447 VKCSettingWorldCameraの画像更新とEnableXRotaionの説明を追加
  docs/VketCloudSettings/CameraSettings.en.md
  docs/VketCloudSettings/CameraSettings.ja.md
  docs/VketCloudSettings/img/CameraSettings_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation, Enhancement

#450 VKCItemPlaneの画像更新と複数項目追加
  docs/VKCComponents/VKCItemPlane.en.md
  docs/VKCComponents/VKCItemPlane.ja.md
  docs/VKCComponents/img/HEOPlane_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 2, Documentation

#446 mkdocs-deployのcheckoutをv2ではなくv3を使用
  .github/workflows/mkdocs-deploy.yml
Labels: Review effort [1-5]: 2, Enhancement, Configuration changes

#451 Heliscriptの重複していた項目を削除
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_date.en.md
  docs/hs/hs_class_date.ja.md
Labels: Review effort [1-5]: 1, Documentation, Enhancement

#454 GUIToolsインストール手順で、無限にインストールが終わらない場合があるので、Unityプロジェクトを再起動することで解決することがある旨を追記
  docs/GUITools/Setup.en.md
  docs/GUITools/Setup.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#448 VKC Setting Avatar: 画像およびIcon説明を更新
  docs/VketCloudSettings/AvatarSettings.en.md
  docs/VketCloudSettings/AvatarSettings.ja.md
  docs/VketCloudSettings/img/AvatarSettings_1.jpg
Labels: Review effort [1-5]: 1, Documentation

#459 VKC/HEO コンポーネント 概要：Item, Nodeについて概要を追記
  docs/VKCComponents/VKCHEOCorrespondenceTable.en.md
  docs/VKCComponents/VKCHEOCorrespondenceTable.ja.md
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#460 SDKの導入方法 画像＆説明文更新
  docs/AboutVketCloudSDK/OperatingEnvironment.en.md
  docs/AboutVketCloudSDK/OperatingEnvironment.ja.md
  docs/AboutVketCloudSDK/SetupSDK_external.en.md
  docs/AboutVketCloudSDK/SetupSDK_external.ja.md
  docs/AboutVketCloudSDK/img/ApiCompatibilityLevelSetting.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_2_jp.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_3.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_4_en.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_4_jp.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_5.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_6_en.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_6_jp.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_7_en.jpg
  docs/AboutVketCloudSDK/img/InstallationWizard_7_jp.jpg
  docs/AboutVketCloudSDK/img/LightMapEncoding.jpg
  docs/AboutVketCloudSDK/img/SDKVersionManager_1.jpg
  docs/AboutVketCloudSDK/img/SDKVersionManager_3_en.jpg
  docs/AboutVketCloudSDK/img/SDKVersionManager_3_jp.jpg
  docs/AboutVketCloudSDK/img/SDKVersionManager_4_en.jpg
  docs/AboutVketCloudSDK/img/SDKVersionManager_4_jp.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_.png
  docs/AboutVketCloudSDK/img/SetupSDK_External_01.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_02.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_03.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_04.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_05.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_06.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_07.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_08.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_09.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_10.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_11.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_12.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_13.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_14.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_15.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_16.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_17.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_18.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_19.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_20.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_21.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_22.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_23.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_24.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_25.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_26.jpg
  docs/AboutVketCloudSDK/img/linear.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Documentation

#470 VKCItemBackgroundTexture画像更新と複数項目を追加
  docs/VKCComponents/VKCItemBackgroundTexture.en.md
  docs/VKCComponents/VKCItemBackgroundTexture.ja.md
  docs/VKCComponents/img/HEOBackgroundTexture_1.jpg
  docs/VKCComponents/img/HEOBackgroundTexture_2.jpg
  docs/VKCComponents/img/HEOBackgroundTexture_3.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#473 VKCItemTextplaneの画像更新と複数項目追加
  docs/VKCComponents/VKCItemTextPlane.en.md
  docs/VKCComponents/VKCItemTextPlane.ja.md
  docs/VKCComponents/img/HEOTextPlane_1.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 2, Documentation

#474 HEOAudio: 設定項目・説明を12.3仕様に更新
  docs/HEOComponents/HEOAudio.en.md
  docs/HEOComponents/HEOAudio.ja.md
  docs/HEOComponents/img/HEOAudio_01.jpg
  docs/HEOComponents/img/HEOAudio_1_en.jpg
  docs/HEOComponents/img/HEOAudio_1_jp.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 2, Documentation

#475 VKC Item Audio: 設定項目・説明を13.4仕様に更新
  docs/VKCComponents/VKCItemAudio.en.md
  docs/VKCComponents/VKCItemAudio.ja.md
  docs/VKCComponents/img/HEOAudio_1_en.jpg
  docs/VKCComponents/img/HEOAudio_1_jp.jpg
  docs/VKCComponents/img/VKCItemAudio_01.jpg
  docs/VKCComponents/img/VKCItemAudio_02_en.jpg
  docs/VKCComponents/img/VKCItemAudio_02_jp.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#476 HEOShowFlag: 設定項目・説明を12.3仕様に更新
  docs/HEOComponents/HEOShowFlag.en.md
  docs/HEOComponents/HEOShowFlag.ja.md
  docs/HEOComponents/img/HEOShowFlag.jpg
  docs/HEOComponents/img/HEOShowFlag.png
  docs/HEOComponents/img/HEOShowFlagJP.jpg
  docs/HEOComponents/img/HEOShowFlag_01.jpg
  docs/HEOComponents/img/HEOShowFlag_02.jpg
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-12.3.ja.md
Labels: Review effort [1-5]: 1, Documentation

#477 VKC Attribute Show Flag: 設定項目・説明を13.4仕様に更新
  docs/VKCComponents/VKCAttributeShowFlag.en.md
  docs/VKCComponents/VKCAttributeShowFlag.ja.md
  docs/VKCComponents/img/HEOShowFlag.jpg
  docs/VKCComponents/img/HEOShowFlag.png
  docs/VKCComponents/img/HEOShowFlagJP.jpg
  docs/VKCComponents/img/VKCAttributeShowFlag_01.jpg
  docs/VKCComponents/img/VKCAttributeShowFlag_02.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 2, Documentation

#479 VKCItemParticleの画像更新と複数項目追加
  docs/VKCComponents/VKCItemParticle.en.md
  docs/VKCComponents/VKCItemParticle.ja.md
  docs/VKCComponents/img/HEOParticle.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 2, Documentation

#478 VKCItemCameraの画像更新と複数項目追加
  docs/VKCComponents/VKCItemCamera.en.md
  docs/VKCComponents/VKCItemCamera.ja.md
  docs/VKCComponents/img/HEOCamera_1.jpg
  docs/VKCComponents/img/HEOCamera_2.jpg
  docs/VKCComponents/img/HEOCamera_3.jpg
  docs/VKCComponents/img/HEOCamera_4.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#480 SetupAccount: 英訳を追加 (v12.3)
  docs/AboutVketCloudSDK/SetupAccount.en.md
  docs/changelog/changelog-12.3.en.md
Labels: Review effort [1-5]: 1, Documentation

#481 SetupAccount: 英訳を追加 (v13.4)
  docs/AboutVketCloudSDK/SetupAccount.en.md
  docs/changelog/changelog-12.3.en.md
  docs/changelog/changelog-13.4.en.md
Labels: Review effort [1-5]: 1, Documentation

#485 HSMessageクラスページを追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_hsmessage.en.md
  docs/hs/hs_class_hsmessage.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#486 Lib13.7のリリースノート追加
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/releasenote/releasenote-13.7.en.md
  docs/releasenote/releasenote-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#489 VKC Item Spot: 文言と画像を修正
  docs/VKCComponents/VKCItemSpot.en.md
  docs/VKCComponents/VKCItemSpot.ja.md
  docs/VKCComponents/img/HEOSpot_1.jpg
  docs/VKCComponents/img/HEOSpot_2.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#484 VKC Item Area Collider: 文言と画像を修正
  docs/VKCComponents/VKCItemAreaCollider.en.md
  docs/VKCComponents/VKCItemAreaCollider.ja.md
  docs/VKCComponents/img/HEOAreaCollider.jpg
  docs/VKCComponents/img/VKCItemAreaCollider_01.jpg
  docs/VKCComponents/img/VKCItemAreaCollider_02.jpg
  docs/VKCComponents/img/VKCItemAreaCollider_03.jpg
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
Labels: Review effort [1-5]: 1, Documentation

#493 IsLoadingとIsLoadedの対応するオブジェクトタイプからVKC Item Audioを外す
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1, Documentation

#488 【13.7】Js入稿機能
  docs/WorldMakingGuide/JsUpload.en.md
  docs/WorldMakingGuide/JsUpload.ja.md
  docs/WorldMakingGuide/img/JsUpload_1.jpg
  docs/WorldMakingGuide/img/JsUpload_2.jpg
  docs/WorldMakingGuide/img/JsUpload_3.jpg
  docs/WorldMakingGuide/img/JsUpload_4.jpg
  docs/WorldMakingGuide/img/JsUpload_5.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#487 【13.7】Install Wizard新規機能追加
  docs/AboutVketCloudSDK/SetupSDK_external.en.md
  docs/AboutVketCloudSDK/SetupSDK_external.ja.md
  docs/AboutVketCloudSDK/img/SetupSDK_External_10.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_27.jpg
  docs/AboutVketCloudSDK/img/SetupSDK_External_28.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#482 HeliScript - 英訳を追加 (v13.4)
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_date.en.md
  docs/hs/hs_class_date.ja.md
  docs/hs/hs_component.en.md
  docs/hs/hs_component.ja.md
  docs/hs/hs_delegate.en.md
  docs/hs/hs_statement_control.en.md
  docs/hs/hs_string.en.md
  docs/hs/hs_system_function_camera.en.md
  docs/hs/hs_system_function_commondialog.en.md
  docs/hs/hs_system_function_gui_HSGUIModel.en.md
  docs/hs/hs_system_function_gui_HSGUIModel.ja.md
  docs/hs/hs_system_function_rendering.en.md
  docs/hs/hs_var.en.md
  docs/hs/hs_var.ja.md
Labels: Review effort [1-5]: 2, Documentation

#495 HeliScript - 英訳を追加 (v12.3)
  docs/changelog/changelog-12.3.en.md
  docs/hs/hs_delegate.en.md
  docs/hs/hs_statement_control.en.md
  docs/hs/hs_string.en.md
  docs/hs/hs_system_function_camera.en.md
  docs/hs/hs_system_function_commondialog.en.md
  docs/hs/hs_var.en.md
Labels: Review effort [1-5]: 2, Documentation

#496 Itemクラスの説明とItemのユーティリティにあるhsItemGetの関数説明を更新 #494
  docs/changelog/changelog-13.4.en.md
  docs/changelog/changelog-13.4.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1, Documentation
