Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-12, with the labels that each got.

#561 ワールド制作ガイド/ロードが完了したら開く扉のページのレイアウトが崩れている
  docs/WorldMakingGuide/DoorOpensAfterLoad.en.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#565 【課題解決Wiki】【実務 / Unity】HEOBackGroundTextureの使い方
  docs/VKCComponents/VKCItemBackgroundTexture.en.md
  docs/VKCComponents/VKCItemBackgroundTexture.ja.md
  docs/WorldMakingGuide/BackgroundTexture.en.md
  docs/WorldMakingGuide/BackgroundTexture.ja.md
  docs/WorldMakingGuide/img/BackgroundTexture_0.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_1.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_2.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_3.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_4.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_5.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_6.jpg
  docs/WorldMakingGuide/img/BackgroundTexture_7.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2

#566 【課題解決Wiki】【実務 / Unity】ライトスキャタリング
  docs/WorldMakingGuide/LightScattering.en.md
  docs/WorldMakingGuide/LightScattering.ja.md
  docs/WorldMakingGuide/img/LightScattering00.jpg
  docs/WorldMakingGuide/img/LightScattering01.jpg
  docs/WorldMakingGuide/img/LightScattering02.jpg
  docs/WorldMakingGuide/img/LightScattering03.jpg
  docs/WorldMakingGuide/img/LightScattering04.jpg
  docs/WorldMakingGuide/img/LightScattering05.jpg
  docs/WorldMakingGuide/img/LightScattering06.jpg
  docs/WorldMakingGuide/img/LightScattering07.jpg
  docs/WorldMakingGuide/img/LightScattering08.jpg
  docs/WorldMakingGuide/img/LightScattering09.jpg
  docs/WorldMakingGuide/img/LightScattering10.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#567 hs_system_function_textchat.htmlはSDK12.3.4以降利用できないことを記載
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/hs_system_function_textchat.en.md
  docs/hs/hs_system_function_textchat.ja.md
Labels: In Review, Review effort [1-5]: 1

#568 SDK14系HeliScript変更部分の更新
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/hs_class_date.en.md
  docs/hs/hs_class_date.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_class_player.ja.md
  docs/hs/hs_class_timespan.en.md
  docs/hs/hs_class_timespan.ja.md
  docs/hs/hs_component.en.md
  docs/hs/hs_component.ja.md
  docs/hs/hs_struct_quaternion.en.md
  docs/hs/hs_struct_quaternion.ja.md
  docs/hs/hs_system_function_commondialog.en.md
  docs/hs/hs_system_function_commondialog.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
  docs/hs/hs_system_function_input.en.md
  docs/hs/hs_system_function_input.ja.md
  docs/hs/hs_system_function_js.en.md
  docs/hs/hs_system_function_js.ja.md
  docs/hs/hs_system_function_math.en.md
  docs/hs/hs_system_function_math.ja.md
  docs/hs/hs_system_function_net.en.md
  docs/hs/hs_system_function_net.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 3

#569 ローカルビルドだと、ログインやAPI周りの連携はできないことを記載する
  docs/FirstStep/BuildAndRun.en.md
  docs/FirstStep/BuildAndRun.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: In Review, Review effort [1-5]: 1

#570 【課題解決Wiki】【実務 / Unity】プレイヤーに追従するテキストの実装
  docs/WorldMakingGuide/PlayerFollowText.en.md
  docs/WorldMakingGuide/PlayerFollowText.ja.md
  docs/WorldMakingGuide/img/PlayerFollowText_01.jpg
  docs/WorldMakingGuide/img/PlayerFollowText_02.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#573 【実務 / Activity】モーション付きアクティビティクラスを実装する
  docs/WorldMakingGuide/ActivityWithMotion.en.md
  docs/WorldMakingGuide/ActivityWithMotion.ja.md
  docs/WorldMakingGuide/img/ActivityWithMotion00.jpg
  docs/WorldMakingGuide/img/ActivityWithMotion01.jpg
  docs/WorldMakingGuide/img/ActivityWithMotion02.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#576 【課題解決Wiki】【実務 / Unity】HEOShadow
  docs/WorldMakingGuide/HEOShadow.en.md
  docs/WorldMakingGuide/HEOShadow.ja.md
  docs/WorldMakingGuide/img/HEOShadow_01.jpg
  docs/WorldMakingGuide/img/HEOShadow_02.jpg
  docs/WorldMakingGuide/img/HEOShadow_03.jpg
  docs/WorldMakingGuide/img/HEOShadow_04.jpg
  docs/WorldMakingGuide/img/HEOShadow_05.jpg
  docs/WorldMakingGuide/img/HEOShadow_06.jpg
  docs/WorldMakingGuide/img/HEOShadow_07.jpg
  docs/WorldMakingGuide/img/HEOShadow_08.jpg
  docs/WorldMakingGuide/img/HEOShadow_09.jpg
  docs/WorldMakingGuide/img/HEOShadow_10.jpg
  docs/WorldMakingGuide/img/HEOShadow_11.jpg
  docs/WorldMakingGuide/img/HEOShadow_12.jpg
  docs/WorldMakingGuide/img/HEOShadow_13.jpg
  docs/WorldMakingGuide/img/HEOShadow_14.jpg
  docs/WorldMakingGuide/img/HEOShadow_15.jpg
  docs/WorldMakingGuide/img/HEOShadow_16.jpg
  docs/WorldMakingGuide/img/HEOShadow_17.jpg
  docs/WorldMakingGuide/img/HEOShadow_18.jpg
  docs/WorldMakingGuide/img/HEOShadow_19.jpg
  docs/WorldMakingGuide/img/HEOShadow_20.jpg
  docs/WorldMakingGuide/img/HEOShadow_21.jpg
  docs/WorldMakingGuide/img/HEOShadow_22.jpg
  docs/WorldMakingGuide/img/HEOShadow_23.jpg
  docs/WorldMakingGuide/img/HEOShadow_24.jpg
  docs/WorldMakingGuide/img/HEOShadow_25.jpg
  docs/WorldMakingGuide/img/HEOShadow_26.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: In Review, Documentation

#579 【実務 / Activity】サブシーン(アクティビティ)のコンポーネントメソッドをメインシーンから実行する
  docs/WorldMakingGuide/ExecuteActivityJsonMethod.en.md
  docs/WorldMakingGuide/ExecuteActivityJsonMethod.ja.md
  docs/WorldMakingGuide/img/ExecuteActivityJsonMethod.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#578 【課題解決Wiki】【実務 / HeliScript】特定の条件下でのみ入場時効果音を鳴らす
  docs/WorldMakingGuide/SoundEffectEntrance.en.md
  docs/WorldMakingGuide/SoundEffectEntrance.ja.md
  docs/WorldMakingGuide/img/SoundEffect_Entrance_1.jpg
  docs/WorldMakingGuide/img/SoundEffect_Entrance_2.jpg
  docs/WorldMakingGuide/img/SoundEffect_Entrance_3.jpg
  docs/WorldMakingGuide/img/SoundEffect_Entrance_4.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2

#580 ActivityCanvas実装時、既存UI・入力欄の消し方
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/RemoveDefaultUI.en.md
  docs/hs/RemoveDefaultUI.ja.md
  docs/hs/img/RemoveDefaultUI00.jpg
  docs/hs/img/RemoveDefaultUI01.jpg
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#575 【Crewオススメ】VketCloudSDK導入・エラー解決法大全
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/troubleshooting/InstallingDeeplink.en.md
  docs/troubleshooting/InstallingDeeplink.ja.md
  docs/troubleshooting/img/InstallingDeeplink_6.jpg
  docs/troubleshooting/img/InstallingDeeplink_7.jpg
Labels: In Review, Review effort [1-5]: 2, Documentation

#574 エンジンで出力されるエラー一覧
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/troubleshooting/BuildError.en.md
  docs/troubleshooting/BuildError.ja.md
Labels: In Review, Review effort [1-5]: 2, Documentation

#583 Delete heliscript funciton from SDK15 or later
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_component.en.md
  docs/hs/hs_component.ja.md
Labels: Review effort [1-5]: 2
