Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-10, with the labels that each got.

#519 index: World Builderの紹介を追記
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  docs/index.en.md
  docs/index.ja.md
Labels: Review effort [1-5]: 1, Documentation

#520 【VKC Node】SDKマニュアルの画像がHEO表記のままになっている
  docs/VKCComponents/VKCNodeLODLevel.ja.md
  docs/VKCComponents/VKCNodeMirror.en.md
  docs/VKCComponents/VKCNodeMirror.ja.md
  docs/VKCComponents/VKCNodeShadow.en.md
  docs/VKCComponents/VKCNodeShadow.ja.md
  docs/VKCComponents/img/HEOAnimation_1.jpg
  docs/VKCComponents/img/HEOAnimation_2.jpg
  docs/VKCComponents/img/HEOAnimation_3.jpg
  docs/VKCComponents/img/HEOAnimation_4.jpg
  docs/VKCComponents/img/HEOCylinderCollider_01.jpg
  docs/VKCComponents/img/HEOCylinderCollider_03.jpg
  docs/VKCComponents/img/HEOLODLevel.jpg
  docs/VKCComponents/img/HEOMeshCollider_1.jpg
  docs/VKCComponents/img/HEOMeshCollider_2.jpg
  docs/VKCComponents/img/HEOMeshCollider_3.jpg
  docs/VKCComponents/img/HEOMirror_1.jpg
  docs/VKCComponents/img/HEOMirror_6.jpg
  docs/VKCComponents/img/HEOMirror_7.jpg
  docs/VKCComponents/img/HEOObjectType.jpg
  docs/VKCComponents/img/HEOShadow_1.jpg
  docs/VKCComponents/img/HEOShadow_2.jpg
  docs/VKCComponents/img/HEOShadow_3.jpg
  docs/VKCComponents/img/HEOShadow_4.jpg
  docs/VKCComponents/img/HEOUVScroller.jpg
  docs/VKCComponents/img/HEOUVScrollerSample.jpg
  docs/VKCComponents/img/HEOVideoTrigger_1.jpg
  docs/VKCComponents/img/HEOVideoTrigger_2.jpg
  docs/VKCComponents/img/HEOVideoTrigger_3.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation

#522 VKCAttributeClickGuideの画像をHEO表記からVKC表記に変更
  docs/VKCComponents/VKCAttributeClickGuide.en.md
  docs/VKCComponents/VKCAttributeClickGuide.ja.md
  docs/VKCComponents/img/HEOClickGuide_1.jpg
  docs/VKCComponents/img/HEOClickGuide_3.jpg
  docs/VKCComponents/img/HEOClickGuide_5.jpg
  docs/VKCComponents/img/HEOClickGuide_6.jpg
  docs/VKCComponents/img/HEOClickGuide_7.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_1.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_2.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_3.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_4.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_5.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_6.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_7.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_8.jpg
  docs/VKCComponents/img/VKCAttributeClickGuide_9.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1, Documentation

#523 VKCNodeMirrorの文章をSDK13.7版に合わせる
  docs/VKCComponents/VKCNodeMirror.en.md
  docs/VKCComponents/VKCNodeMirror.ja.md
  docs/VKCComponents/img/HEOMirror_14.jpg
  docs/VKCComponents/img/HEOMirror_15.jpg
  docs/VKCComponents/img/HEOMirror_6.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: In Review, Review effort [1-5]: 2, Documentation

#524 [14.1]ご意見・バグ報告フォームのページを追加
  docs/changelog/changelog-14.1.en.md
  docs/changelog/changelog-14.1.ja.md
  docs/troubleshooting/Comment_Bug_Reports.en.md
  docs/troubleshooting/Comment_Bug_Reports.ja.md
  docs/troubleshooting/img/Comments_01.jpg
  docs/troubleshooting/img/Comments_02.jpg
  docs/troubleshooting/img/Comments_03.jpg
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#525 アセットストアからダウンロードするアバターの設定方法
  docs/WorldMakingGuide/ImportAssetStore.en.md
  docs/WorldMakingGuide/ImportAssetStore.ja.md
  docs/WorldMakingGuide/img/ImproveAssetStore_1.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_2.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_3.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_4.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_5.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_6.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_7.jpg
  docs/WorldMakingGuide/img/ImproveAssetStore_8.jpg
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1, Documentation

#527 [14.1]RenderingSettingsへToneMapの設定項目追記
  docs/VketCloudSettings/RenderingSettings.en.md
  docs/VketCloudSettings/RenderingSettings.ja.md
  docs/VketCloudSettings/img/RenderingSettings_1.jpg
  docs/VketCloudSettings/img/RenderingSettings_6.jpg
  docs/changelog/changelog-14.1.en.md
  docs/changelog/changelog-14.1.ja.md
Labels: Review effort [1-5]: 2, Documentation

#532 Pickable Item
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/VKCComponents/img/VKCItemObject_1.jpg
  docs/VKCComponents/img/VKCItemObject_8.jpg
  docs/changelog/changelog-14.1.en.md
  docs/changelog/changelog-14.1.ja.md
Labels: Review effort [1-5]: 1

#533 VketCloudGUITools用の標準搭載のAddEssential機能の説明を追加
  docs/GUITools/HowToUse.en.md
  docs/GUITools/HowToUse.ja.md
  docs/GUITools/img/GUITools_HowToUse_14.jpg
  docs/changelog/changelog-14.1.en.md
  docs/changelog/changelog-14.1.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1
