Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2024-11, with the labels that each got.

#535 BrokerAPI: サンプルコード修正(14.2)
  docs/ExternalAPI/BrokerAPI.en.md
  docs/ExternalAPI/BrokerAPI.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2

#537 HierarchyIcons: ヒエラルキーアイコンページ追加
  docs/WorldEditingTips/HierarchyIcons.en.md
  docs/WorldEditingTips/HierarchyIcons.ja.md
  docs/WorldEditingTips/img/HierarchyIcons_01_HEOSpot.png
  docs/WorldEditingTips/img/HierarchyIcons_02_HEOActivity.png
  docs/WorldEditingTips/img/HierarchyIcons_03_HEOAreaCollider.png
  docs/WorldEditingTips/img/HierarchyIcons_04_HEOObject.png
  docs/WorldEditingTips/img/HierarchyIcons_04_HEOObject_Error.png
  docs/WorldEditingTips/img/HierarchyIcons_04_HEOObject_Warning.png
  docs/WorldEditingTips/img/HierarchyIcons_05_HEOAudio.png
  docs/WorldEditingTips/img/HierarchyIcons_06_HEOParticle.png
  docs/WorldEditingTips/img/HierarchyIcons_07_HEOCamera.png
  docs/WorldEditingTips/img/HierarchyIcons_08_HEOField.png
  docs/WorldEditingTips/img/HierarchyIcons_09_HEOPlane.png
  docs/WorldEditingTips/img/HierarchyIcons_1.jpg
  docs/WorldEditingTips/img/HierarchyIcons_10_HEOText.png
  docs/WorldEditingTips/img/HierarchyIcons_11_VKCAttributeScript.png
  docs/WorldEditingTips/img/HierarchyIcons_12_VKCAttribute_Property.png
  docs/WorldEditingTips/img/HierarchyIcons_13_VKCAttributeActionTrigger.png
  docs/WorldEditingTips/img/HierarchyIcons_14_VKCAttributeClickableUI.png
  docs/WorldEditingTips/img/HierarchyIcons_15_VKCNode_VideoTrigger.png
  docs/WorldEditingTips/img/HierarchyIcons_16_VKCNodeCollider.png
  docs/WorldEditingTips/img/HierarchyIcons_17_VKCItemBackgroundTexture.png
  docs/WorldEditingTips/img/HierarchyIcons_18_VKCNodeUVScroller.png
  docs/WorldEditingTips/img/HierarchyIcons_19_VKCNodeAlphaAnimation.png
  docs/WorldEditingTips/img/HierarchyIcons_20_VKCNodeRotateAnimation.png
  docs/WorldEditingTips/img/HierarchyIcons_21_VKCNodeCylinderCollider.png
  docs/WorldEditingTips/img/HierarchyIcons_22_VKCNodeBlendShapeTranslator.png
  docs/WorldEditingTips/img/HierarchyIcons_23_VKCNodeLODLevel.png
  docs/WorldEditingTips/img/HierarchyIcons_24_VKCNodeMeshCollider.png
  docs/WorldEditingTips/img/HierarchyIcons_25_VKCNodeMirror.png
  docs/WorldEditingTips/img/HierarchyIcons_26_VKCNodeReflectionProbeType.png
  docs/WorldEditingTips/img/HierarchyIcons_27_VKCNodeShadow.png
  docs/WorldEditingTips/img/HierarchyIcons_28_VKCAttributeShowFlag.png
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#538 VKC Item FieldとVKC Item Objectの新しい項目(Force Raycast Check DisableとForce Collider Disabled)の追加
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/VKCComponents/img/VKCItemField3.jpg
  docs/VKCComponents/img/VKCItemObject_2.jpg
  docs/changelog/changelog-14.1.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: Review effort [1-5]: 1

#542 【14.2】GetNodeIndexByNameとGetNodePosByIndexとGetNodeNameByIndexのメソッドに、見つからなかったときに返す値を追記する
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1

#543 【13.7】GetNodeIndexByNameとGetNodePosByIndexとGetNodeNameByIndexのメソッドに、見つからなかったときに返す値を追記する
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Review effort [1-5]: 1

#544 【14.2】VKC Item TextPlaneにおいて、正規表現("\n"以外）使えないことを記述する
  docs/VKCComponents/VKCItemTextPlane.en.md
  docs/VKCComponents/VKCItemTextPlane.ja.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: Review effort [1-5]: 1

#545 【13.7】VKC Item TextPlaneにおいて、正規表現("\n"以外）使えないことを記述する
  docs/VKCComponents/VKCItemTextPlane.en.md
  docs/VKCComponents/VKCItemTextPlane.ja.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 2

#540 右クリックメニューのドキュメント更新
  docs/WorldEditingTips/QuickMenu.en.md
  docs/WorldEditingTips/QuickMenu.ja.md
  docs/WorldEditingTips/img/QuickMenu_1.jpg
  docs/changelog/changelog-14.1.en.md
  docs/changelog/changelog-14.1.ja.md
Labels: Review effort [1-5]: 1

#546 リリースノート14.3を追加
  docs/releasenote/releasenote-14.3.en.md
  docs/releasenote/releasenote-14.3.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1

#549 【14.2】ホームページのURLを修正
  mkdocs.yml
Labels: Review effort [1-5]: 1

#550 【13.7】 ホームページのURLを修正
  mkdocs.yml
Labels: Review effort [1-5]: 1

#552 【13.7】コライダーターゲットがコライダータイプがコライダーの時にしか設定できない旨を追加する
  docs/VKCComponents/VKCNodeCollider.en.md
  docs/VKCComponents/VKCNodeCollider.ja.md
  docs/changelog/changelog-13.7.en.md
  docs/changelog/changelog-13.7.ja.md
Labels: Review effort [1-5]: 1

#551 【14.2】コライダーターゲットがコライダータイプがコライダーの時にしか設定できない旨を追加する
  docs/VKCComponents/VKCNodeCollider.en.md
  docs/VKCComponents/VKCNodeCollider.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: Review effort [1-5]: 1

#555 【HeliScript】hsWebReload関数の説明を加える(14.2のみ)
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/hs/hs_system_function.en.md
  docs/hs/hs_system_function.ja.md
Labels: Review effort [1-5]: 1

#556 Lib14.4のリリースノートを追加
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/releasenote/releasenote-14.2.en.md
  docs/releasenote/releasenote-14.2.ja.md
  docs/releasenote/releasenote-14.3.en.md
  docs/releasenote/releasenote-14.3.ja.md
  docs/releasenote/releasenote-14.4.en.md
  docs/releasenote/releasenote-14.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1

#553 【課題解決Wiki】SphereColliderをクリックしても反応しない問題
  docs/FAQ/SphereCollider.en.md
  docs/FAQ/SphereCollider.ja.md
  docs/FAQ/img/SphereCollider_1.jpg
  docs/FAQ/img/SphereCollider_2.jpg
  docs/FAQ/img/SphereCollider_3.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2

#554 【課題解決Wiki】ビルド時に"Index was out of range. Must be non-negative and less than the size of the collection."が表示される
  docs/FAQ/UV2MeshBuildError.en.md
  docs/FAQ/UV2MeshBuildError.ja.md
  docs/FAQ/img/UV2MeshBuildError_1.jpg
  docs/FAQ/img/UV2MeshBuildError_2.jpg
  docs/FAQ/img/UV2MeshBuildError_3.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 1

#558 【課題解決Wiki】【実務 / Unity】ロードが完了したら開く扉ギミック
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/WorldMakingGuide/DoorOpensAfterLoad.en.md
  docs/WorldMakingGuide/DoorOpensAfterLoad.ja.md
  docs/WorldMakingGuide/img/DoorOpensAfterLoad00.jpg
  docs/WorldMakingGuide/img/DoorOpensAfterLoad01.jpg
  docs/WorldMakingGuide/img/DoorOpensAfterLoad03.jpg
  docs/WorldMakingGuide/img/DoorOpensAfterLoad04.jpg
  docs/WorldMakingGuide/img/DoorOpensAfterLoad06.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#559 【課題解決Wiki】【実務 / Unity】UnityとVketCloudの見た目を揃える方法
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/heoexporter/he_align_unity_to_vketcloud.en.md
  docs/heoexporter/he_align_unity_to_vketcloud.ja.md
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_1.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_10.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_2.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_3.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_4.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_5.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_6.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_7.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_8.jpg
  docs/heoexporter/he_image/he_align_unity_to_vketcloud_9.jpg
Labels: Review effort [1-5]: 2
