Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2025-04, with the labels that each got.

#667 [15.3]Canvasでダイアログ外をクリック(タップ)したときにダイアログを閉じる機能を実装する
  docs/WorldMakingGuide/CloseCanvas.en.md
  docs/WorldMakingGuide/CloseCanvas.ja.md
  docs/WorldMakingGuide/img/CloseCanvas01.jpg
  docs/WorldMakingGuide/img/CloseCanvas02.jpg
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#666 ワールド制作ガイドの目次ページを作成
  docs/WorldMakingGuide/WorldMakingGuide.en.md
  docs/WorldMakingGuide/WorldMakingGuide.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#671 VKC Node Refleciton Probe Type説明を追加
  docs/VKCComponents/VKCNodeReflectionProbeType.en.md
  docs/VKCComponents/VKCNodeReflectionProbeType.ja.md
  docs/VKCComponents/img/VKCNodeReflectionProbeType_1.gif
  docs/VKCComponents/img/VKCNodeReflectionProbeype_1.jpg
  docs/VKCComponents/img/VKCNodeReflectionProbeype_2.jpg
  docs/VKCComponents/img/VKCNodeReflectionProbeype_3.jpg
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Review effort 1/5

#669 ブローカーAPIの記事で古くなっている関数が使われているのを修正
  docs/ExternalAPI/BrokerAPI.en.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Review effort 1/5

#673 15.3のリンクエラーを修正
  docs/VKCComponents/VKCAttributeClickGuide.en.md
  docs/VKCComponents/VKCAttributeProperty.ja.md
  docs/VKCComponents/VKCItemField.en.md
  docs/VKCComponents/VKCItemField.ja.md
  docs/VKCComponents/VKCItemObject.en.md
  docs/WorldMakingGuide/VKCAttributeProperty.ja.md
  mkdocs.yml
Labels: Review effort 2/5

#649 FAQページ整理
  docs/FAQ/FAQ_home.en.md
  docs/FAQ/FAQ_home.ja.md
  mkdocs.yml
Labels: Review effort 2/5

#675 hotfix ワールド制作ガイドの記事項目が二重になっている問題の修正
  mkdocs.yml
Labels: Review effort 2/5

#676 LDOC-704 LDOC-1099 14系以前ですと、MeshRenderer無しだとVKCNodeMeshColliderが正常動作しない
  docs/VKCComponents/VKCNodeMeshCollider.en.md
  docs/VKCComponents/VKCNodeMeshCollider.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: In Review, Documentation, Review effort 1/5

#684 Feature/sdk 15.3/add hs math description
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_system_function_math.en.md
  docs/hs/hs_system_function_math.ja.md
Labels: Documentation, Review effort 1/5

#683 Feature/sdk 15.3/add description to getworldrotate
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Documentation, Review effort 1/5

#678 Feature/sdk 15.3/edit switch statement description
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_statement_control.en.md
  docs/hs/hs_statement_control.ja.md
Labels: Documentation, Review effort 2/5

#679 Feature/sdk 15.3/add create avatar file note
  docs/VketCloudSettings/AvatarSettings.en.md
  docs/VketCloudSettings/AvatarSettings.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Documentation, Review effort 1/5

#680 Refactor/sdk 15.3/instance variable description
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_scope_def.en.md
  docs/hs/hs_scope_def.ja.md
  docs/hs/hs_statement_def.en.md
  docs/hs/hs_statement_def.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#682 Feature/sdk 15.3/add note to delegate
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_delegate.en.md
  docs/hs/hs_delegate.ja.md
Labels: Documentation, Review effort 2/5

#685 [15.3]SDKログインページのUntiyバージョン表記修正
  docs/AboutVketCloudSDK/LoginSDK.en.md
  docs/AboutVketCloudSDK/LoginSDK.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Documentation, Review effort 1/5

#670 VKC Attribute Propertyの関連リンクURLの表記を修正
  docs/VKCComponents/VKCAttributeProperty.en.md
  docs/VKCComponents/VKCAttributeProperty.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Review effort 1/5

#686 15.4リリースノートの追加
  docs/changelog/changelog-15.4.en.md
  docs/changelog/changelog-15.4.ja.md
  docs/releasenote/releasenote-15.4.en.md
  docs/releasenote/releasenote-15.4.ja.md
Labels: Review effort 1/5

#689 [15.3]クイックメニューからSkyboxを作成する手順追記
  docs/WorldMakingGuide/Skybox.en.md
  docs/WorldMakingGuide/Skybox.ja.md
  docs/WorldMakingGuide/img/Skybox_6.jpg
  docs/WorldMakingGuide/img/Skybox_7.jpg
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Documentation, Review effort 2/5

#672 VRM File Creator記事を追加
  docs/SDKTools/VRMFileCreator.en.md
  docs/SDKTools/VRMFileCreator.ja.md
  docs/SDKTools/img/VRMFileCreator_1.jpg
  docs/SDKTools/img/VRMFileCreator_2.jpg
  docs/SDKTools/img/VRMFileCreator_3.jpg
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  mkdocs.yml
Labels: Review effort 1/5

#688 [15.3]AppleSilicon版Unityを使用した際の不具合についての注記を追記
  docs/AboutVketCloudSDK/LoginSDK.en.md
  docs/AboutVketCloudSDK/LoginSDK.ja.md
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
Labels: Documentation, Review effort 1/5

#687 Feature/sdk 15.3/chs system assert
  docs/changelog/changelog-15.3.en.md
  docs/changelog/changelog-15.3.ja.md
  docs/hs/hs_assertion_function.en.md
  docs/hs/hs_assertion_function.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#691 [14.5]PlaneアイテムのZbiasを動的に変更するページを追加
  docs/WorldMakingGuide/WorldMakingGuide.en.md
  docs/WorldMakingGuide/WorldMakingGuide.ja.md
  docs/WorldMakingGuide/Zbias.en.md
  docs/WorldMakingGuide/Zbias.ja.md
  docs/WorldMakingGuide/img/zbias.jpg
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#692 [14.5]現状Boxコライダー付きのGameObjectはVKCNodeColliderがアタッチされていなくとも物理衝突するので、その内容をコライダーの使い方の記事に追加
  docs/WorldMakingGuide/Collider.en.md
  docs/WorldMakingGuide/Collider.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Review effort 2/5
