Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2025-06, with the labels that each got.

#703 Lib15.6リリースノート追加
  docs/changelog/changelog-15.6.en.md
  docs/changelog/changelog-15.6.ja.md
  docs/releasenote/releasenote-15.5.ja.md
  docs/releasenote/releasenote-15.6.en.md
  docs/releasenote/releasenote-15.6.ja.md
  mkdocs.yml
Labels: Review effort 2/5

#702 [14.5]Social Iconsを追加
  .claude/settings.local.json
  custom_theme/main.html
  docs/images/Favicon.png
  docs/images/HikkyLogo.svg
  docs/images/HikkyLogo_Black.png
  docs/images/HikkyLogo_Color.png
  docs/images/HikkyLogo_White.png
  docs/images/HikkySquareLogo_Black.png
  docs/images/HikkySquareLogo_Color.png
  docs/images/HikkySquareLogo_White.png
  docs/images/LineLogo.svg
  docs/images/NoteLogo.svg
  docs/images/QiitaLogo.svg
  docs/images/VketCloudIcon_Black.png
  docs/images/VketCloudIcon_Color.png
  docs/images/VketCloudIcon_White.png
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: Review effort 3/5

#700 [14.5] リンク問題を修正
  docs/VKCComponents/VKCNodeCollider.en.md
  docs/VKCComponents/VKCNodeCollider.ja.md
  docs/WorldMakingGuide/VKCAttributeProperty.en.md
  docs/troubleshooting/BuildError.ja.md
Labels: Review effort 1/5

#705 [14.5]誤字2件を修正
  docs/Actions/WindowState/SetGenericWindowState.ja.md
  docs/releasenote/releasenote-14.5.ja.md
Labels: Documentation, Review effort 1/5

#699 [14.5]フィードバック機能再実装
  custom_theme/main.html
Labels: Review effort 2/5

#724 fix: change Spatium code from "Default" to "default" in BrokerAPI docs
  CLAUDE.md
  docs/ExternalAPI/BrokerAPI.en.md
  docs/ExternalAPI/BrokerAPI.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Review effort 1/5

#720 hsファイルの改行コードはLFのみ許容する
  CLAUDE.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Review effort 1/5

#718 カプセルコライダーはエリアコライダー用途にしか対応していないことを仕様として記述する
  CLAUDE.md
  docs/VKCComponents/VKCNodeCylinderCollider.en.md
  docs/VKCComponents/VKCNodeCylinderCollider.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Review effort 2/5
