Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2025-02, with the labels that each got.

#602 ロードが完了すると画面が真っ暗になる
  docs/FAQ/Load_Blackout.en.md
  docs/FAQ/Load_Blackout.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  mkdocs.yml
Labels: In Review

#607 コンポーネント / コールバック関数の説明での説明表記を更新
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/hs/hs_component.en.md
  docs/hs/hs_component.ja.md
Labels: In Review, Review effort [1-5]: 2

#608 particleeditor: パーティクルエディターにおける入力不具合および修正予定について記載
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/particleeditor/pe_about_particleeditor.en.md
  docs/particleeditor/pe_about_particleeditor.ja.md
  docs/particleeditor/pe_about_properties.en.md
  docs/particleeditor/pe_about_properties.ja.md
Labels: Review effort [1-5]: 2

#606 【課題解決Wiki】テクスチャの差し替えが正常に出来ない
  docs/WorldMakingGuide/ReplaceTexture.en.md
  docs/WorldMakingGuide/ReplaceTexture.ja.md
  docs/WorldMakingGuide/img/ReplaceTexture01.jpg
  docs/WorldMakingGuide/img/ReplaceTexture02.jpg
  docs/WorldMakingGuide/img/ReplaceTexture03.jpg
  docs/WorldMakingGuide/img/ReplaceTexture04.jpg
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#609 Voice Attenuation/音声減衰の項目をオフにすると、ボイチャ機能ごと動作しなくなる
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/troubleshooting/VoiceAttenuationTrouble.en.md
  docs/troubleshooting/VoiceAttenuationTrouble.ja.md
  docs/troubleshooting/img/VoiceAttenuation00.jpg
  docs/troubleshooting/img/VoiceAttenuation01.jpg
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#610 OnReceiveCustomStateとOnReceiveCustomDataのコールバックについて、送信したプレイヤーには届かないことを追記
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/hs/hs_system_function_net.en.md
  docs/hs/hs_system_function_net.ja.md
Labels: Documentation, Review effort 2/5

#612 Prop Animationのページで、system系関数を外す
  docs/WorldMakingGuide/PropAnimation.en.md
  docs/WorldMakingGuide/PropAnimation.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Review effort 2/5

#613 VKC Item Objectとパーティクルエディタの不具合注記に14.5.6で修正済の旨追記
  docs/VKCComponents/VKCItemObject.en.md
  docs/VKCComponents/VKCItemObject.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/particleeditor/pe_about_particleeditor.en.md
  docs/particleeditor/pe_about_particleeditor.ja.md
Labels: Documentation, Review effort 2/5
