Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2025-03, with the labels that each got.

#614 【画像圧縮 - 知識】[ASTC] [ETC2]とは
  docs/WorldOptimization/AstcAndEtc2.en.md
  docs/WorldOptimization/AstcAndEtc2.ja.md
  docs/WorldOptimization/img/AstcAndEtc200.jpg
  docs/WorldOptimization/img/AstcAndEtc201.jpg
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#617 ログインやAPI連携はローカルビルドでは動作しないことに関して詳細を加える
  docs/FirstStep/BuildAndRun.en.md
  docs/FirstStep/BuildAndRun.ja.md
  docs/FirstStep/img/BuildAndRun_1.jpg
  docs/FirstStep/img/BuildAndRun_2.jpg
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: In Review, Review effort 1/5

#618 hsCanvasWorldToScreenPosに関して説明を修正する
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Review effort 1/5

#620 【実務/Ingame】Lib13以降　追加モーション設定
  docs/FAQ/AddMotionsAfterLib13.en.md
  docs/FAQ/AddMotionsAfterLib13.ja.md
  docs/FAQ/img/AddMotionsAfterLib1300.jpg
  docs/FAQ/img/AddMotionsAfterLib1301.jpg
  docs/FAQ/img/AddMotionsAfterLib1302.jpg
  docs/FAQ/img/AddMotionsAfterLib1303.jpg
  docs/FAQ/img/AddMotionsAfterLib1304.jpg
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: In Review, Documentation, Review effort 2/5

#621 効果音の初回再生が遅い問題の解消のページを追加
  docs/FAQ/FirstSE.en.md
  docs/FAQ/FirstSE.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Review effort 2/5

#622 VketCloud公式サイトへの導線変更
  docs/AboutVketCloudSDK/SetupAvatar.en.md
  docs/AboutVketCloudSDK/SetupAvatar.ja.md
  docs/AboutVketCloudSDK/img/SetupAvatar_01.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_01_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_02.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_02_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_03.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_03_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_04.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_04_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_05.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_05_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_06.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_07.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_1_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_1_ja.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_2_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_2_ja.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_3_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_3_ja.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_4_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_4_ja.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_5_en.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_5_ja.jpg
  docs/AboutVketCloudSDK/img/SetupAvatar_6.jpg
  docs/FAQ/ProfileImage.en.md
  docs/FAQ/ProfileImage.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/troubleshooting/GeneralChecklist.en.md
  docs/troubleshooting/GeneralChecklist.ja.md
Labels: Documentation, Review effort 2/5

#624 HeliScriptでCanvas要素を制御する
  docs/WorldMakingGuide/HeliscriptCanvas.en.md
  docs/WorldMakingGuide/HeliscriptCanvas.ja.md
  docs/WorldMakingGuide/img/HeliscriptCanvas01.jpg
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#626 Cameraクラス
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_system_function_camera.en.md
  docs/hs/hs_system_function_camera.ja.md
Labels: In Review, Documentation, Review effort 1/5

#628 Raycast追加
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_struct_hsraycasthit.en.md
  docs/hs/hs_struct_hsraycasthit.ja.md
  docs/hs/hs_system_function_raycast.en.md
  docs/hs/hs_system_function_raycast.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#629 add : cookie doc
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_system_function_cookie.en.md
  docs/hs/hs_system_function_cookie.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#627 JS入稿:「サンプルワールド」から「チュートリアルシーン」に置き換え
  docs/WorldMakingGuide/JsUpload.en.md
  docs/WorldMakingGuide/JsUpload.ja.md
  docs/WorldMakingGuide/JsUpload_TutorialScene.en.md
  docs/WorldMakingGuide/JsUpload_TutorialScene.ja.md
  docs/WorldMakingGuide/img/JSUpload_TutorialScene.gif
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#631 Get Current Weather Using Web API
  docs/WorldMakingGuide/JsUpload_FetchCurrentWeather.en.md
  docs/WorldMakingGuide/JsUpload_FetchCurrentWeather.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#637 Bugfix/sdk 14.5/merge conflict bug
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#630 add: restrict world entry time doc
  docs/WorldMakingGuide/JsUpload_RestrictEntryTime.en.md
  docs/WorldMakingGuide/JsUpload_RestrictEntryTime.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#632 refactor: heliscript parse json
  docs/ExternalAPI/HeliScriptJsonParse.en.md
  docs/ExternalAPI/HeliScriptJsonParse.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#633 組み込み関数 - レンダリング
  docs/changelog/changelog-15.1.en.md
  docs/changelog/changelog-15.1.ja.md
  docs/hs/hs_system_function_rendering.en.md
  docs/hs/hs_system_function_rendering.ja.md
  mkdocs.yml
Labels: In Review, Documentation, Review effort 3/5

#636 add description to make quaternion euler
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_struct_quaternion.en.md
  docs/hs/hs_struct_quaternion.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#644 [15.1]hs_class_itemにSetVolumeとGetVolume追記
  docs/changelog/changelog-15.1.en.md
  docs/changelog/changelog-15.1.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Documentation, Review effort 2/5

#646 [15.1]hsItemCreateCloneおよびhsItemDestroyCloneクラスを追加
  docs/changelog/changelog-15.1.en.md
  docs/changelog/changelog-15.1.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
Labels: Documentation, Review effort 1/5

#648 15.0と15.1のリリースノートを追加
  docs/releasenote/releasenote-15.0.en.md
  docs/releasenote/releasenote-15.0.ja.md
  docs/releasenote/releasenote-15.1.en.md
  docs/releasenote/releasenote-15.1.ja.md
  mkdocs.yml
Labels: Review effort 2/5

#651 Bugfix/sdk 14.5/merge conflict bug 2
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#653 [15.2]Raycast追加
  docs/changelog/changelog-15.2.en.md
  docs/changelog/changelog-15.2.ja.md
  docs/hs/hs_class_item.en.md
  docs/hs/hs_class_item.ja.md
  docs/hs/hs_struct_hsraycasthit.en.md
  docs/hs/hs_struct_hsraycasthit.ja.md
  docs/hs/hs_system_function_raycast.en.md
  docs/hs/hs_system_function_raycast.ja.md
  mkdocs.yml
Labels: Documentation, Review effort 1/5

#635 組み込み関数 - GUI
  docs/changelog/changelog-15.1.en.md
  docs/changelog/changelog-15.1.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: In Review, Documentation, Review effort 2/5

#634 Feature/sdk 15.1/add hs get text area content size
  docs/changelog/changelog-15.1.en.md
  docs/changelog/changelog-15.1.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Documentation, Review effort 1/5

#647 VKC Node Collider, VKC Item Area Colliderの画像のリンク切れ・文言を修正
  docs/VKCComponents/VKCItemAreaCollider.ja.md
  docs/VKCComponents/VKCNodeCollider.en.md
  docs/VKCComponents/VKCNodeCollider.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
Labels: Documentation, Review effort 1/5

#658 Feature/sdk 15.3/リリースノートの追加
  docs/releasenote/releasenote-14.5.en.md
  docs/releasenote/releasenote-14.5.ja.md
  docs/releasenote/releasenote-15.3.en.md
  docs/releasenote/releasenote-15.3.ja.md
  mkdocs.yml
Labels: Review effort 1/5

#638 hsCanvasSetGUIText: cannot use comma in text
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Documentation, Review effort 1/5

#639 Refactor/sdk 14.5/equality operator descriptions
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_operator.en.md
  docs/hs/hs_operator.ja.md
Labels: Documentation, Review effort 2/5

#640 add replacetexture method's trouble shooting case
  docs/WorldMakingGuide/ReplaceTexture.en.md
  docs/WorldMakingGuide/ReplaceTexture.ja.md
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_class_item.en.md
  mkdocs.yml
Labels: Documentation, Review effort 2/5

#641 Feature/sdk 14.5/add this keyword description
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_var.en.md
  docs/hs/hs_var.ja.md
Labels: Documentation, Review effort 2/5

#642 Feature/sdk 14.5/add block statement description
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_statement_control.en.md
  docs/hs/hs_statement_control.ja.md
Labels: Documentation, Review effort 2/5

#645 Refactor/sdk 14.5/hs canvas reset toggle default description
  docs/changelog/changelog-14.5.en.md
  docs/changelog/changelog-14.5.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Documentation, Review effort 1/5
