Repository VRHIKKY/VketCloudSDK_Documents, pull requests merged in 2025-01, with the labels that each got.

#590 sdk-13.4 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Review effort [1-5]: 2

#588 sdk-14.2 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Review effort [1-5]: 2

#589 sdk-13.7 - hs_system_function_gui: hsAddGUIButtonの関数説明を修正
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
Labels: Review effort [1-5]: 2

#584 Split関数についてのFAQページを追加
  docs/FAQ/HS_Split.en.md
  docs/FAQ/HS_Split.ja.md
  docs/FAQ/img/HSSplit.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2

#586 Pngの大文字制限の文言を削除
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
Labels: Review effort [1-5]: 1

#591 mkdocs.yml: 全角スペーストル
  mkdocs.yml
Labels: Review effort [1-5]: 1

#592 SDK14.4のリリースノートを追加
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/releasenote/releasenote-14.4.en.md
  docs/releasenote/releasenote-14.4.ja.md
Labels: Review effort [1-5]: 2

#581 【課題解決Wiki】iPhone単体でChromeのデベロッパーツールのコンソールを確認する方法 追加
  docs/WorldMakingGuide/iPhoneConsole.en.md
  docs/WorldMakingGuide/iPhoneConsole.ja.md
  docs/WorldMakingGuide/img/iPhoneConsole01.jpg
  docs/WorldMakingGuide/img/iPhoneConsole02.jpg
  docs/WorldMakingGuide/img/iPhoneConsole03.jpg
  docs/WorldMakingGuide/img/iPhoneConsole04.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#582 【課題解決Wiki】ワールド入室後にマルチプレイができない時の確認ポイント 追加
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/troubleshooting/MultiplayerTroubleshooting.en.md
  docs/troubleshooting/MultiplayerTroubleshooting.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#587 【課題解決Wiki】CanvasUI表示機能付きアクティビティクラスを作る
  docs/FAQ/HS_Split.en.md
  docs/FAQ/HS_Split.ja.md
  docs/FAQ/img/HSSplit.jpg
  docs/WorldMakingGuide/ActivityWithCanvasUI.en.md
  docs/WorldMakingGuide/ActivityWithCanvasUI.ja.md
  docs/WorldMakingGuide/UnityGuidelines.en.md
  docs/WorldMakingGuide/UnityGuidelines.ja.md
  docs/WorldMakingGuide/img/ActivityWithCanvasUI01.jpg
  docs/WorldMakingGuide/img/ActivityWithCanvasUI02.jpg
  docs/WorldMakingGuide/img/ActivityWithCanvasUI03.jpg
  docs/WorldMakingGuide/img/ActivityWithCanvasUI04.jpg
  docs/changelog/changelog-14.2.en.md
  docs/changelog/changelog-14.2.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/hs/hs_system_function_gui.en.md
  docs/hs/hs_system_function_gui.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#598 [14.4]【課題解決Wiki】iPhone単体でChromeのデベロッパーツールのコンソールを確認する方法 追加
  docs/WorldMakingGuide/iPhoneConsole.en.md
  docs/WorldMakingGuide/iPhoneConsole.ja.md
  docs/WorldMakingGuide/img/iPhoneConsole01.jpg
  docs/WorldMakingGuide/img/iPhoneConsole02.jpg
  docs/WorldMakingGuide/img/iPhoneConsole03.jpg
  docs/WorldMakingGuide/img/iPhoneConsole04.jpg
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#595 VKCNodeMirrorのMaterialのShaderがUnlitとVketChanlitしか使えないことを記載する
  docs/VKCComponents/VKCNodeMirror.en.md
  docs/VKCComponents/VKCNodeMirror.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
Labels: In Review, Review effort [1-5]: 1, Documentation

#597 [14.4]【課題解決Wiki】ワールド入室後にマルチプレイができない時の確認ポイント 追加
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/troubleshooting/MultiplayerTroubleshooting.en.md
  docs/troubleshooting/MultiplayerTroubleshooting.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#594 Data型の特殊仕様ページを追加
  docs/FAQ/DateSpecialSpecifications.en.md
  docs/FAQ/DateSpecialSpecifications.ja.md
  docs/FAQ/img/DateSpecialSpecifications.jpg
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2

#599 【課題解決Wiki】HeliScriptでJsonを読み込む
  docs/ExternalAPI/HeliScriptJsonParse.en.md
  docs/ExternalAPI/HeliScriptJsonParse.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  mkdocs.yml
Labels: Review effort [1-5]: 2, Documentation

#600 【課題解決Wiki】一度バージョンアップ後、過去バージョンに巻き戻すと、Unityが起動しなくなった場合の解消法を追記
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/troubleshooting/VersionUpdateTroubleshooting.en.md
  docs/troubleshooting/VersionUpdateTroubleshooting.ja.md
  docs/troubleshooting/img/VersionUpdateTroubleshooting_13.jpg
Labels: Documentation

#601 ローディング画面の途中で「バイナリ出力に失敗しました」というエラーが出てフリーズする
  docs/WorldMakingGuide/BinaryOutputError.en.md
  docs/WorldMakingGuide/BinaryOutputError.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  docs/hs/hs_statement_def.en.md
  docs/hs/hs_statement_def.ja.md
  mkdocs.yml
Labels: In Review, Documentation

#604 SetupSDK_external: レジストリ情報におけるScope(s)の表記を修正
  docs/AboutVketCloudSDK/SetupSDK_external.en.md
  docs/AboutVketCloudSDK/SetupSDK_external.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
Labels: Review effort [1-5]: 2

#603 エラーの出ない不具合の解決方法
  docs/FAQ/ErrorNotDisplayed.en.md
  docs/FAQ/ErrorNotDisplayed.ja.md
  docs/FAQ/LoadingStack.en.md
  docs/FAQ/LoadingStack.ja.md
  docs/FAQ/NotReflectedDuringBuild.en.md
  docs/FAQ/NotReflectedDuringBuild.ja.md
  docs/FAQ/img/ErrorNotDisplayed.jpg
  docs/FAQ/img/NotReflectedDuringBuild.jpg
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
  mkdocs.yml
Labels: In Review, Review effort [1-5]: 2, Documentation

#605 WorldUpload - ワールド公開設定に関する記述を更新
  docs/FirstStep/WorldUpload.en.md
  docs/FirstStep/WorldUpload.ja.md
  docs/changelog/changelog-14.4.en.md
  docs/changelog/changelog-14.4.ja.md
Labels: Review effort [1-5]: 2
